import NavigationBar from '@/components/NavigationBar';
import Footer from '@/components/Footer'
import '@/styles/globals.css'
import { Montserrat } from 'next/font/google'
import Head from 'next/head';

const montserratFont = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});

export default function App({ Component, pageProps }) {
  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

    <main className={`${montserratFont.variable} font-sans bg-light dark:bg-dark w-full min-h-screen`}>
      <NavigationBar />
      <Component {...pageProps} />
      <Footer />
    </main>
    </>
  );
}
